- name: configuring mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name:
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb server
    package:
      name: mongodb-org
      state: present
  - name: allow remote users
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  - name: start and enable mongodb
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
