- name: configuring catalogue
  hosts: catalogue
  become: yes
  tasks: 
  - name: enable nodejs
    command: dnf module enable nodejs:20 -y
  - name: install nodejs
    package:
      name: nodejs
      state: present
  - name: create roboshop system user
    user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"
  - name: Remove directory
    file:
      path: /app
      state: absent
  - name: delete catalogue.zip in thmp directory
    file:
      path: /tmp/catalogue.zip
      state: absent
  - name: create app directory
    file:
      path: /app
      state: directory
  - name: download catalogue
    get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip
  - name: unzip catalogue
    unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  - name: Install dependencies
    community.general.npm:
      path: /app
  - name: copy template module
    template:
      src: catalogue.service.j2
      dest: /etc/systemd/system/catalogue.service
  - name: copy mongo repo
    copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb client
    package:
      name: mongodb-mongosh
      state: present
  - name: check index created or not
    shell: mongosh --host "{{ MONGODB_HOST }}" --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output
    tags: 
    - mongodb
  - name: load the products
    shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: catalogue_output.stdout < 0
    tags: 
    - mongodb
  # - name: start the service
  #   service: 
      