- name: configuring catalogue
  hosts: catalogue
  become: yes
  tasks: 
  - name: enable nodejs
    command: dnf module enable nodejs:20 -y
  - name: install nodejs
    package:
      name: nodejs
      state: present
  - name: create roboshop system user
    user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"
  # - name: Remove directory
  #   file:
  #     path: /app
  #     state: absent
  # - name: delete catalogue.zip in thmp directory
  #   file:
  #     path: /tmp/catalogue.zip
  #     state: absent
  # - name: create app directory
  #   file:
  #     path: /app
  #     state: directory
  # - name: download catalogue
  #   get_url:
  #     url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
  #     dest: /tmp/catalogue.zip