- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: enable nginx:1.24
    command: dnf module enable nginx:1.24 -y 
  - name: install enginx
    package: 
      name: nginx
      state: present
  - name: remove html directory
    file:
      path: /usr/share/nginx/html/
      state: absent
  - name: delete frontend.zip in thmp directory
    file:
      path: /tmp/frontend.zip
      state: absent
  - name: create app directory
    file:
      path: /usr/share/nginx/html/
      state: directory
  - name: download payment
    get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip
  - name: unzip frontend
    unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html/
      remote_src: yes
  - name: remove nginx default conf
    file:
      path: /etc/nginx/nginx.conf
      state: absent
  - name: copy ninx conf
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
  - name: enable and start the service
    service: 
      name: nginx
      state: restarted
      enabled: yes

