[local]
localhost

[mongodb]
mongodb.learndevopskills.shop

[redis]
redis.learndevopskills.shop

[mysql]
mysql.learndevopskills.shop

[rabbitmq]
rabbitmq.learndevopskills.shop

[catalogue]
catalogue.learndevopskills.shop

[frontend]
frontend.learndevopskills.shop