[local]
localhost

[mongodb]
mongodb.learndevopskills.shop

[redis]
redis.learndevopskills.shop

[mysql]
mysql.learndevopskills.shop

[rabbitmq]
rabbitmq.learndevopskills.shop

[catalogue]
catalogue.learndevopskills.shop

[user]
users.learndevopskills.shop

[cart]
cart.learndevopskills.shop

[shipping]
shipping.learndevopskills.shop

[payment]
payment.learndevopskills.shop


[frontend]
frontend.learndevopskills.shop