- name: Roboshop EC2 Instance Creation
  hosts: local
  connection: local
  vars:
    instance: ["mongodb", "redis"]
    ami_id: ami-0220d79f3f480ecf5
    instance_type: "t3.micro"
  tasks:
  - name: Installing roboshop instances
    amazon.aws.ec2_instance:
      name: "roboshop-{{ item }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ ami_id }}"
      security_groups:
      - "roboshop-{{ item }}"
      - roboshop-common
    loop: "{{ instance }}"
    register: ec2_output
  
  # - name:
  #   debug:
  #     msg: "{{ ec2_output }}"

  - name: Create R53 Record
    debug:
      msg: " Instance Name: {{ item.item }} Private IP: {{ item.instance[0].private_ip_address }}"
    loop: "{{ ec2_output.results}}"
